In [53]:
import numpy as np

In [54]:
## 1. NAND w1, w2, theta
## 2. AND w1, w2, theta
## 3. OR w1, w2, theta
## NAND 논리를 출력하는 함수 
## AND 논리를 출력하는 함수 
## OR 논리를 출력하는 함수 
## XOR 논리를 출력하는 함수

In [55]:
X = np.array([[0,0,1,1],[0,1,0,1]]).T

In [56]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [74]:
X[:,0]

array([0, 0, 1, 1])

In [212]:
## 함수
def AND(x):
    W = np.array([[0.1],[0.1]])
    theta = 0.1
    return np.where(np.dot(x,W) > theta,1,0)

def OR(x):
    W = np.array([[0.2],[0.2]])
    theta = 0.1
    return np.where(np.dot(x,W) > theta,1,0)

def NAND(x):
    W = np.array([[0.1],[0.1]])
    theta = 0.2
    return np.where(np.dot(x,W) < theta,1,0)

def XOR(x):
    x = np.c_[NAND(x),OR(x)]
    return AND(x)

In [213]:
print(AND(X))
print(OR(X))
print(NAND(X))
print(XOR(X))

[[0]
 [0]
 [0]
 [1]]
[[0]
 [1]
 [1]
 [1]]
[[1]
 [1]
 [1]
 [0]]
[[0]
 [1]
 [1]
 [0]]


In [153]:
w1s = np.linspace(0.1,1,10)
w2s = np.linspace(0.1,1,10)
thetas = np.linspace(0.1,1,10)
for w1 in w1s:
    for w2 in w2s:
        for theta in thetas:
            result = np.where(X[:,0]*w1+X[:,1]*w2 > theta,1,0)
            if np.sum(result == np.array([0,0,0,1])) == 4:
                print(w1,w2,theta)

0.1 0.1 0.1
0.1 0.2 0.2
0.1 0.30000000000000004 0.30000000000000004
0.1 0.4 0.4
0.1 0.5 0.5
0.1 0.6 0.6
0.1 0.7000000000000001 0.7000000000000001
0.1 0.8 0.8
0.1 0.9 0.9
0.1 1.0 1.0
0.2 0.1 0.2
0.2 0.2 0.2
0.2 0.2 0.30000000000000004
0.2 0.30000000000000004 0.30000000000000004
0.2 0.30000000000000004 0.4
0.2 0.4 0.4
0.2 0.4 0.5
0.2 0.4 0.6
0.2 0.5 0.5
0.2 0.5 0.6
0.2 0.6 0.6
0.2 0.6 0.7000000000000001
0.2 0.7000000000000001 0.7000000000000001
0.2 0.7000000000000001 0.8
0.2 0.7000000000000001 0.9
0.2 0.8 0.8
0.2 0.8 0.9
0.2 0.9 0.9
0.2 0.9 1.0
0.2 1.0 1.0
0.30000000000000004 0.1 0.30000000000000004
0.30000000000000004 0.2 0.30000000000000004
0.30000000000000004 0.2 0.4
0.30000000000000004 0.30000000000000004 0.30000000000000004
0.30000000000000004 0.30000000000000004 0.4
0.30000000000000004 0.30000000000000004 0.5
0.30000000000000004 0.30000000000000004 0.6
0.30000000000000004 0.4 0.4
0.30000000000000004 0.4 0.5
0.30000000000000004 0.4 0.6
0.30000000000000004 0.5 0.5
0.30000000000000004

In [155]:
w1s = np.linspace(0.1,1,10)
w2s = np.linspace(0.1,1,10)
thetas = np.linspace(0.1,1,10)
for w1 in w1s:
    for w2 in w2s:
        for theta in thetas:
            result = np.where(X[:,0]*w1+X[:,1]*w2 > theta,1,0)
            if np.sum(result == np.array([0,1,1,1])) == 4:
                print(w1,w2,theta)

0.2 0.2 0.1
0.2 0.30000000000000004 0.1
0.2 0.4 0.1
0.2 0.5 0.1
0.2 0.6 0.1
0.2 0.7000000000000001 0.1
0.2 0.8 0.1
0.2 0.9 0.1
0.2 1.0 0.1
0.30000000000000004 0.2 0.1
0.30000000000000004 0.30000000000000004 0.1
0.30000000000000004 0.30000000000000004 0.2
0.30000000000000004 0.4 0.1
0.30000000000000004 0.4 0.2
0.30000000000000004 0.5 0.1
0.30000000000000004 0.5 0.2
0.30000000000000004 0.6 0.1
0.30000000000000004 0.6 0.2
0.30000000000000004 0.7000000000000001 0.1
0.30000000000000004 0.7000000000000001 0.2
0.30000000000000004 0.8 0.1
0.30000000000000004 0.8 0.2
0.30000000000000004 0.9 0.1
0.30000000000000004 0.9 0.2
0.30000000000000004 1.0 0.1
0.30000000000000004 1.0 0.2
0.4 0.2 0.1
0.4 0.30000000000000004 0.1
0.4 0.30000000000000004 0.2
0.4 0.4 0.1
0.4 0.4 0.2
0.4 0.4 0.30000000000000004
0.4 0.5 0.1
0.4 0.5 0.2
0.4 0.5 0.30000000000000004
0.4 0.6 0.1
0.4 0.6 0.2
0.4 0.6 0.30000000000000004
0.4 0.7000000000000001 0.1
0.4 0.7000000000000001 0.2
0.4 0.7000000000000001 0.30000000000000004
0.

In [157]:
w1s = np.linspace(0.1,1,10)
w2s = np.linspace(0.1,1,10)
thetas = np.linspace(0.1,1,10)
for w1 in w1s:
    for w2 in w2s:
        for theta in thetas:
            result = np.where(X[:,0]*w1+X[:,1]*w2 < theta,1,0)
            if np.sum(result == np.array([1,1,1,0])) == 4:
                print(w1,w2,theta)

0.1 0.1 0.2
0.1 0.2 0.30000000000000004
0.1 0.30000000000000004 0.4
0.1 0.4 0.5
0.1 0.5 0.6
0.1 0.7000000000000001 0.8
0.1 0.8 0.9
0.1 0.9 1.0
0.2 0.1 0.30000000000000004
0.2 0.2 0.30000000000000004
0.2 0.2 0.4
0.2 0.30000000000000004 0.4
0.2 0.30000000000000004 0.5
0.2 0.4 0.5
0.2 0.4 0.6
0.2 0.5 0.6
0.2 0.6 0.7000000000000001
0.2 0.6 0.8
0.2 0.7000000000000001 0.8
0.2 0.7000000000000001 0.9
0.2 0.8 0.9
0.2 0.8 1.0
0.2 0.9 1.0
0.30000000000000004 0.1 0.4
0.30000000000000004 0.2 0.4
0.30000000000000004 0.2 0.5
0.30000000000000004 0.30000000000000004 0.4
0.30000000000000004 0.30000000000000004 0.5
0.30000000000000004 0.30000000000000004 0.6
0.30000000000000004 0.4 0.5
0.30000000000000004 0.4 0.6
0.30000000000000004 0.4 0.7000000000000001
0.30000000000000004 0.5 0.6
0.30000000000000004 0.5 0.7000000000000001
0.30000000000000004 0.5 0.8
0.30000000000000004 0.6 0.7000000000000001
0.30000000000000004 0.6 0.8
0.30000000000000004 0.6 0.9
0.30000000000000004 0.7000000000000001 0.8
0.3000000000

## bias 값 찾기

In [210]:
"""
w1s = np.linspace(-1,1,10)
w2s = np.linspace(-1,1,10)
thetas = np.linspace(-1,1,10)
for w1 in w1s:
    for w2 in w2s:
        for theta in thetas:
            result = np.where(X[:,0]*w1+X[:,1]*w2 < theta,1,0)
            if (np.sum(result == np.array([1,1,1,0])) == 4) and (theta > 0): 
                print(w1,w2,theta)
"""

0.33333333333333326 0.33333333333333326 0.5555555555555554
0.33333333333333326 0.5555555555555554 0.7777777777777777
0.33333333333333326 0.7777777777777777 1.0
0.5555555555555554 0.33333333333333326 0.7777777777777777
0.5555555555555554 0.5555555555555554 0.7777777777777777
0.5555555555555554 0.5555555555555554 1.0
0.5555555555555554 0.7777777777777777 1.0
0.7777777777777777 0.33333333333333326 1.0
0.7777777777777777 0.5555555555555554 1.0
0.7777777777777777 0.7777777777777777 1.0


In [224]:
### XOR 다른 방법
"""
def XOR(x):
    W1 = np.array([[-0.1,-0.1],[0.2,0.2]])
    W2 = np.array([[0.1],[0.2]])
    b1 = 0.2
    b2 = 0.2
    layer1 = np.where(np.dot(X,W1) > b1,1,0)
    layer2 = np.where(np.dot(layer1,W2) > b2,1,0)
    return layer1,layer2
"""

'\ndef XOR(x):\n    W1 = np.array([[-0.1,-0.1],[0.2,0.2]])\n    W2 = np.array([[0.1],[0.2]])\n    b1 = 0.2\n    b2 = 0.2\n    layer1 = np.where(np.dot(X,W1) > b1,1,0)\n    layer2 = np.where(np.dot(layer1,W2) > b2,1,0)\n    return layer1,layer2\n'

In [ ]:
### XOR 함수 Form
"""
def XOR(x):
    W1 = np.array([[nand],[or_]])
    W2 = np.array([[and_]])
    
    b1 = nand
    b2 = or_
    b3 = and_
    
    s1 = np.where(np.dot(x,W1[:,0]) > b1,1,0)
    s2 = np.where(np.dot(x,W1[:,1]) < b2,1,0)
    s = np.c_[s1,s2]
    return np.where(np.dot(s,W2) > b3,1,0)
    """

In [ ]:
## 함수
def AND(x):
    W = np.array([[0.1],[0.1]])
    theta = 0.1
    return np.where(np.dot(x,W) > theta,1,0)

def OR(x):
    W = np.array([[0.2],[0.2]])
    theta = 0.1
    return np.where(np.dot(x,W) > theta,1,0)

def NAND(x):
    W = np.array([[0.1],[0.1]])
    theta = 0.2
    return np.where(np.dot(x,W) < theta,1,0)

def XOR(x):
    x = np.c_[NAND(x),OR(x)]
    return AND(x)

In [222]:
def XOR(x):
    W1 = np.array([[0.1,0.2],[0.1,0.2]])
    W2 = np.array([[0.1],[0.1]])
    
    b1 = 0.2
    b2 = 0.1
    b3 = 0.1
    
    s1 = np.where(np.dot(x,W1[:,0]) < b1,1,0)
    s2 = np.where(np.dot(x,W1[:,1]) > b2,1,0)
    s = np.c_[s1,s2]

    # return s1,s2
    return np.where(np.dot(s,W2) > b3,1,0)

In [223]:
XOR(X)

array([[0],
       [1],
       [1],
       [0]])

In [225]:
def XOR(x):
    W1 = np.array([[0.1,0.1],[0.1,0.7]])
    W2 = np.array([[0.03],[0.1]])
    
    b1 = 0.17
    b2 = 0.03
    b3 = 0.1
    
    s1 = np.where(np.dot(x,W1[:,0]) < b1,1,0)
    s2 = np.where(np.dot(x,W1[:,1]) > b2,1,0)
    s = np.c_[s1,s2]

    # return s1,s2
    return np.where(np.dot(s,W2) > b3,1,0)

In [226]:
XOR(X)

array([[0],
       [1],
       [1],
       [0]])